version: "3.7"
services: 
  customer_service:
    build: services/customers
    volumes:
      - ./services/customers/src:/var/www/customer_service
    ports: 
      - "5001:5000"
    expose: 
      - "5000"
  orders_service:
    build: services/orders
    volumes:
      - ./services/orders/src:/var/www/orders_service
    ports: 
      - "5002:5000"
    expose: 
      - "5000"
  consul_server:
    image: consul
    hostname: dev-consul
    environment: 
      - CONSUL_ALLOW_PRIVILEGED_PORTS=yes
    ports:
      - "8600:8600"
      - "8500:8500"
      - "8301:8301"
      - "8302:8302"
      - "8300:8300"
    expose: 
      - "8600"
      - "8500"
      - "8301"
      - "8302"
      - "8300"
  
    